// Generated by scripts/generate-snowman-product.mjs. Do not edit.
abstract final class SnowmanProduct {
  static const productName = 'Snowman 360';
  static const commandCenterName = 'Snowman Command Center';
  static const adminName = 'Snowman Operations';
  static const mobileName = 'Snowman Command Center';
  static const tagline = 'Governed intelligence. Always advancing.';
  static const publicDomain = 'snowmanai.org';
  static const supportEmail = 'security@snowmanai.org';
  static const primaryDeepLinkScheme = 'snowman';
  static const legacyDeepLinkScheme = 'buzz';
}

abstract final class SnowmanColors {
  static const midnight = 0xFF10233F;
  static const night = 0xFF071426;
  static const snow = 0xFFFFFFFF;
  static const ice = 0xFFF7FBFF;
  static const frost = 0xFFD8F2FF;
  static const glacier = 0xFF55C2FF;
  static const aurora = 0xFF22C7A9;
  static const ember = 0xFFFF9F43;
  static const slate = 0xFF48627F;
  static const danger = 0xFFDC3C52;
}
